In [19]:
function luDecompNoPiv(A)
    n,m = size(A)
    for k in 1:n-1
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A
end

luDecompNoPiv (generic function with 1 method)

In [175]:
function luDecompParPiv(A)
    n,m = size(A)
    p = Array(1:n)
    for k in 1:n-1
        
        val,ind = findmax(A[k:n,k])
        ind = ind + k - 1
                
        swap = p[k]
        p[k] = p[ind]
        p[ind] = swap
        
        swap = A[k,:]
        A[k,:] = A[ind,:]
        A[ind,:] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p
end

luDecompParPiv (generic function with 1 method)

In [3]:
function luDecompFullPiv(A)
    n,m = size(A)
    p = Array(1:n)
    q = Array(1:m)
    for k in 1:n-1
        
        val,ind = findmax(A[k:n,k:n])
        y = Int(ceil(ind / (n-k+1))) + k-1
        x = ind % (n-k+1) + k-1
        if x == k-1
            x = n
        end
                
        swap = p[k]
        p[k] = p[x]
        p[x] = swap
        
        swap = A[k,:]
        A[k,:] = A[x,:]
        A[x,:] = swap
        
        swap = q[k]
        q[k] = q[y]
        q[y] = swap
        
        swap = A[:,k]
        A[:,k] = A[:,y]
        A[:,y] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p,q
end

luDecompFullPiv (generic function with 1 method)

In [1]:
function luDecompRookPiv(A)
    n,m = size(A)
    p = Array(1:n)
    q = Array(1:m)
    for k in 1:n-1
        
        x = k
        y = k
        t = A[k,k]
        s = 0
        
        while t < maximum(A[k:n,y]) || t < maximum(A[x,k:n])
            if s % 2 == 0
                val,ind = findmax(A[k:n,y])
                x = ind + k - 1
            else
                val,ind = findmax(A[x,k:n])
                y = ind + k - 1
            end
            t = A[x,y]
            s = s + 1
        end
                
        swap = p[k]
        p[k] = p[x]
        p[x] = swap
        
        swap = A[k,:]
        A[k,:] = A[x,:]
        A[x,:] = swap
        
        swap = q[k]
        q[k] = q[y]
        q[y] = swap
        
        swap = A[:,k]
        A[:,k] = A[:,y]
        A[:,y] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p,q
end

luDecompRookPiv (generic function with 1 method)

In [30]:
function luDecompScaParPiv(A)
    n,m = size(A)
    p = Array(1:n)
    for k in 1:n-1
        scaled = zeros(n-k+1)
        for i in k:n
            scaled[i-k+1] = A[i,k]/maximum(A[i,k:n])
        end
        val,ind = findmax(scaled)
        ind = ind + k - 1
                
        swap = p[k]
        p[k] = p[ind]
        p[ind] = swap
        
        swap = A[k,:]
        A[k,:] = A[ind,:]
        A[ind,:] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p
end

luDecompScaParPiv (generic function with 1 method)

In [45]:
function luDecompScaFullPiv(A)
    n,m = size(A)
    p = Array(1:n)
    q = Array(1:m)
    for k in 1:n-1
        
        B = (A[k:n,k:n] ./ maximum(A[k:n,k:n],1)) ./ maximum(A[k:n,k:n],2)
        
        val,ind = findmax(B)
        y = Int(ceil(ind / (n-k+1))) + k-1
        x = ind % (n-k+1) + k-1
        if x == k-1
            x = n
        end
                
        swap = p[k]
        p[k] = p[x]
        p[x] = swap
        
        swap = A[k,:]
        A[k,:] = A[x,:]
        A[x,:] = swap
        
        swap = q[k]
        q[k] = q[y]
        q[y] = swap
        
        swap = A[:,k]
        A[:,k] = A[:,y]
        A[:,y] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p,q
end

luDecompScaFullPiv (generic function with 1 method)

In [5]:
function luDecompScaRookPiv(A)
    n,m = size(A)
    p = Array(1:n)
    q = Array(1:m)
    for k in 1:n-1
        
        B = (A[k:n,k:n] ./ maximum(A[k:n,k:n],1)) ./ maximum(A[k:n,k:n],2)
        
        x = 1
        y = 1
        t = B[1,1]
        s = 0
        
        while t < maximum(B[:,y]) || t < maximum(B[x,:])
            if s % 2 == 0
                val,ind = findmax(B[:,y])
                x = ind
            else
                val,ind = findmax(B[x,:])
                y = ind
            end
            t = B[x,y]
            s = s + 1
        end
        
        x = x + k -1
        y = y + k - 1
                
        swap = p[k]
        p[k] = p[x]
        p[x] = swap
        
        swap = A[k,:]
        A[k,:] = A[x,:]
        A[x,:] = swap
        
        swap = q[k]
        q[k] = q[y]
        q[y] = swap
        
        swap = A[:,k]
        A[:,k] = A[:,y]
        A[:,y] = swap
        
        A[k+1:n,k] = A[k+1:n,k]/A[k,k]
        for i in k+1:n
            for j in k+1:n
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
            end
        end
    end
    return A,p,q
end

luDecompScaRookPiv (generic function with 1 method)

In [12]:
A = rand(1000,1000)
A0 = copy(A)
A,p,q = luDecompScaRookPiv(A)

([0.996488 0.317429 … 0.297928 0.818533; 0.0330155 0.980826 … 0.403776 0.641922; … ; 0.477094 0.101979 … 17.2541 1.59205; 0.338044 0.510589 … 0.485245 -3.27655], [675, 814, 594, 585, 413, 357, 15, 936, 361, 268  …  22, 503, 204, 731, 487, 635, 403, 762, 552, 143], [424, 2, 3, 95, 335, 117, 7, 256, 640, 720  …  976, 678, 583, 667, 995, 453, 819, 233, 738, 758])

In [13]:
n,m = size(A)
L = eye(n,m)+tril(A,-1)
U = triu(A);

In [14]:
A0[p,q] - L*U

1000×1000 Array{Float64,2}:
 0.0  0.0   0.0          0.0   0.0          …   0.0           0.0        
 0.0  0.0   0.0          0.0   0.0              0.0           0.0        
 0.0  0.0  -1.11022e-16  0.0   0.0              0.0           1.11022e-16
 0.0  0.0   0.0          0.0   0.0              0.0           0.0        
 0.0  0.0   1.11022e-16  0.0   0.0              0.0           0.0        
 0.0  0.0  -1.11022e-16  0.0   0.0          …  -1.11022e-16   0.0        
 0.0  0.0   0.0          0.0   0.0              0.0           0.0        
 0.0  0.0  -1.11022e-16  0.0   1.11022e-16      0.0           2.22045e-16
 0.0  0.0   0.0          0.0   0.0             -1.11022e-16  -1.11022e-16
 0.0  0.0   0.0          0.0   0.0              5.55112e-17   2.22045e-16
 0.0  0.0   0.0          0.0   1.11022e-16  …   0.0           0.0        
 0.0  0.0   0.0          0.0  -6.93889e-18      0.0           2.22045e-16
 0.0  0.0   0.0          0.0   5.55112e-17     -1.11022e-16   2.22045e-16
 ⋮        

In [55]:
B = rand(8,5)
findmax(B)

(0.9696531334863081, 5)

In [56]:
findmax((B ./ maximum(B,1)) ./ maximum(B,2))

(1.2812824917884578, 30)

In [58]:
(B ./ maximum(B,1)) ./ maximum(B,2)

8×5 Array{Float64,2}:
 0.0902665  0.433449  1.02075   0.910535   1.19221 
 0.14002    1.01052   0.252813  1.19221    1.19221 
 0.79416    0.966959  1.17631   0.0600017  0.125561
 1.0313     0.691354  0.702245  0.319072   0.704308
 1.0313     1.0313    0.257481  0.903773   0.303994
 0.954714   1.25754   0.514409  1.28128    0.240293
 0.466015   0.944191  1.17631   0.184953   0.83065 
 1.0313     0.448245  0.537587  0.686424   0.432329

In [59]:
B

8×5 Array{Float64,2}:
 0.0681076  0.268207  0.675232  0.509851   0.778131 
 0.113881   0.674015  0.180271  0.719604   0.838778 
 0.607561   0.60667   0.78898   0.0340661  0.0830933
 0.793257   0.436107  0.473568  0.182136   0.468623 
 0.969653   0.795204  0.212247  0.630622   0.247246 
 0.587842   0.634996  0.277689  0.585476   0.127985 
 0.384146   0.63829   0.850119  0.113145   0.592304 
 0.87453    0.311723  0.399672  0.431977   0.317129 